apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: dgweblication
data:
  my-key: my-value
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: dgweblication
data:
  my-key: my-value
 
