---
- name: Install Grafana
  hosts: web
  become: yes

  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafana repo  to the sources list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present

  - name: update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is Started and Enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: yes
      state: started
